import 'package:flutter/material.dart';

class CurrencyOption {
  final String code;
  final String name;
  final String simbol;
  final Image icon;
  const CurrencyOption(this.code, this.name, this.simbol, this.icon);

  @override
  String toString() => code; // útil para debug
}

/// Lista fija de opciones
List<CurrencyOption> kCurrencyOptions = [
  CurrencyOption(
    'AED',
    'United Arab Emirates dirham',
    'Dhs.',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'AFN',
    'Afghan afghani',
    '؋',
    Image.asset('assets/images/flags/afn.webp'),
  ),
  CurrencyOption(
    'ALL',
    'Albanian lek',
    'Lek',
    Image.asset('assets/images/flags/all.webp'),
  ),
  CurrencyOption(
    'AMD',
    'Armenian dram',
    'Դ',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ANG',
    'Netherlands Antillean guilder',
    'ƒ',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'AOA',
    'Angolan kwanza',
    'AOA',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ARS',
    'Argentine peso',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'AUD',
    'Australian dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'AWG',
    'Aruban florin',
    'ƒ',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'AZN',
    'Azerbaijani manat',
    'ман',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BAM',
    'Bosnia and Herzegovina convertible mark',
    'KM',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BBD',
    'Barbados dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BDT',
    'Bangladeshi taka',
    '৳',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BGN',
    'Bulgarian lev',
    'лв',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BHD',
    'Bahraini dinar',
    'BD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BIF',
    'Burundian franc',
    'FBu',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BMD',
    'Bermudian dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BND',
    'Brunei dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BOB',
    'Boliviano',
    '\$b',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BRL',
    'Brazilian real',
    'R\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BSD',
    'Bahamian dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BTN',
    'Bhutanese ngultrum',
    'BTN',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BWP',
    'Botswana pula',
    'P',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BYR',
    'Belarusian ruble',
    'Br',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'BZD',
    'Belize dollar',
    'BZ\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CAD',
    'Canadian dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CDF',
    'Congolese franc',
    'CDF',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CHF',
    'Swiss franc',
    'Fr.',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CLP',
    'Chilean peso',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CNY',
    'Chinese yuan',
    '¥',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'COP',
    'Colombian peso',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'COU',
    'Unidad de Valor Real',
    'COU',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CRC',
    'Costa Rican colon',
    '₡',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CUC',
    'Cuban convertible peso',
    'CUC',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CUP',
    'Cuban peso',
    '₱',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CVE',
    'Cape Verde escudo',
    'CVE',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'CZK',
    'Czech koruna',
    'Kč',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'DJF',
    'Djiboutian franc',
    'Fdj',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'DKK',
    'Danish krone',
    'kr',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'DOP',
    'Dominican peso',
    'RD\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'DZD',
    'Algerian dinar',
    'DZD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'EGP',
    'Egyptian pound',
    '£',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ERN',
    'Eritrean nakfa',
    'ERN',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ETB',
    'Ethiopian birr',
    'Br',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'EUR',
    'Euro',
    '€',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'FJD',
    'Fiji dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'FKP',
    'Falkland Islands pound',
    '£',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GBP',
    'Pound sterling',
    '£',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GEL',
    'Georgian lari',
    'GEL',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GHS',
    'Ghanaian cedi',
    'GH₵',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GIP',
    'Gibraltar pound',
    '£',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GMD',
    'Gambian dalasi',
    'GMD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GNF',
    'Guinean franc',
    'GNF',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GTQ',
    'Guatemalan quetzal',
    'Q',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'GYD',
    'Guyanese dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'HKD',
    'Hong Kong dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'HNL',
    'Honduran lempira',
    'L',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'HRK',
    'Croatian kuna',
    'kn',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'HTG',
    'Haitian gourde',
    'HTG',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'HUF',
    'Hungarian forint',
    'Ft',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'IDR',
    'Indonesian rupiah',
    'Rp',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ILS',
    'Israeli new sheqel',
    '₪',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'INR',
    'Indian rupee',
    'IN₨',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'IQD',
    'Iraqi dinar',
    'IQD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'IRR',
    'Iranian rial',
    '﷼',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ISK',
    'Icelandic króna',
    'kr',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'JMD',
    'Jamaican dollar',
    'J\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'JOD',
    'Jordanian dinar',
    'JOD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'JPY',
    'Japanese yen',
    '¥',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KES',
    'Kenyan shilling',
    'KES',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KGS',
    'Kyrgyzstani som',
    'KGS',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KHR',
    'Cambodian riel',
    '៛',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KMF',
    'Comoro franc',
    'CF',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KPW',
    'North Korean won',
    '₩',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KRW',
    'South Korean won',
    '₩',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KWD',
    'Kuwaiti dinar',
    'KWD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KYD',
    'Cayman Islands dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'KZT',
    'Kazakhstani tenge',
    '〒',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LAK',
    'Lao kip',
    '₭',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LBP',
    'Lebanese pound',
    '£',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LKR',
    'Sri Lanka rupee',
    '₨',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LRD',
    'Liberian dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LSL',
    'Lesotho loti',
    'M',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LTL',
    'Lithuanian litas',
    'Lt',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LVL',
    'Latvian lats',
    'Ls',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'LYD',
    'Libyan dinar',
    'LD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MAD',
    'Moroccan dirham',
    'MD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MDL',
    'Moldovan leu',
    'MDL',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MGA',
    'Malagasy ariary',
    'MGA',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MKD',
    'Macedonian denar',
    'ден',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MMK',
    'Myanma kyat',
    'K',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MNT',
    'Mongolian tugrik',
    '₮',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MOP',
    'Macanese pataca',
    'MOP',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MRO',
    'Mauritanian ouguiya',
    'MRO',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MUR',
    'Mauritian rupee',
    '₨',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MVR',
    'Maldivian rufiyaa',
    'MRf',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MWK',
    'Malawian kwacha',
    'MK',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MXN',
    'Mexican peso',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MYR',
    'Malaysian ringgit',
    'RM',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'MZN',
    'Mozambican metical',
    'MT',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'NAD',
    'Namibian dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'NGN',
    'Nigerian naira',
    '₦',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'NIO',
    'Cordoba oro',
    'C\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'NOK',
    'Norwegian krone',
    'kr',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'NPR',
    'Nepalese rupee',
    '₨',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'NZD',
    'New Zealand dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'OMR',
    'Omani rial',
    '﷼',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'PAB',
    'Panamanian balboa',
    'B/.',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'PEN',
    'Peruvian nuevo sol',
    'S/.',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'PGK',
    'Papua New Guinean kina',
    'K',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'PHP',
    'Philippine peso',
    'Php',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'PKR',
    'Pakistani rupee',
    '₨',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'PLN',
    'Polish złoty',
    'zł',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'PYG',
    'Paraguayan guaraní',
    'Gs',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'QAR',
    'Qatari rial',
    '﷼',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'RON',
    'Romanian new leu',
    'lei',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'RSD',
    'Serbian dinar',
    'Дин.',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'RUB',
    'Russian rouble',
    'руб',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'RWF',
    'Rwandan franc',
    'RF',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SAR',
    'Saudi riyal',
    '﷼',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SBD',
    'Solomon Islands dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SCR',
    'Seychelles rupee',
    '₨',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SDG',
    'Sudanese pound',
    'SDG',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SEK',
    'Swedish krona/kronor',
    'kr',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SGD',
    'Singapore dollar',
    'S\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SHP',
    'Saint Helena pound',
    '£',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SLL',
    'Sierra Leonean leone',
    'SLL',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SOS',
    'Somali shilling',
    'S',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SRD',
    'Surinamese dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'STD',
    'São Tomé and Príncipe dobra',
    'STD',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SYP',
    'Syrian pound',
    '£',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'SZL',
    'Lilangeni',
    'E',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'THB',
    'Thai baht',
    '฿',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TJS',
    'Tajikistani somoni',
    'TJS',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TMT',
    'Turkmenistani manat',
    'TMT',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TND',
    'Tunisian dinar',
    'TND',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TOP',
    'Tongan paʻanga',
    'TOP',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TRY',
    'Turkish lira',
    'TL',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TTD',
    'Trinidad and Tobago dollar',
    'TT\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TWD',
    'New Taiwan dollar',
    'NT\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'TZS',
    'Tanzanian shilling',
    'TZS',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'UAH',
    'Ukrainian hryvnia',
    '₴',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'UGX',
    'Ugandan shilling',
    'USh',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'USD',
    'United States dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'UYU',
    'Uruguayan peso',
    '\$U',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'UZS',
    'Uzbekistan som',
    'UZS',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'VEF',
    'Venezuelan bolívar fuerte',
    'Bs',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'VND',
    'Vietnamese đồng',
    '₫',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'VUV',
    'Vanuatu vatu',
    'VUV',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'WST',
    'Samoan tala',
    'WST',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'XAF',
    'CFA franc BEAC',
    'FCFA',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'XCD',
    'East Caribbean dollar',
    '\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'XDR',
    'Special Drawing Rights',
    'XDR',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'XPF',
    'CFP franc',
    'F',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'YER',
    'Yemeni rial',
    '﷼',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ZAR',
    'South African rand',
    'R',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ZMK',
    'Zambian kwacha',
    'ZMK',
    Image.asset('assets/images/flags/aed.webp'),
  ),
  CurrencyOption(
    'ZWL',
    'Zimbabwe dollar',
    'Z\$',
    Image.asset('assets/images/flags/aed.webp'),
  ),
];
